[package]
name = "aptos-pump-fun"
version = "1.0.0"
authors = []

[addresses]
pump = "0x2c19ca9fb773e90f102349d6c07a1676bcebca86a53ca21a1ed3c44659d748c9"
dead = "0xdead"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

#[dependencies.Liquidswap]
#git = "https://github.com/pontem-network/liquidswap.git"
#rev = "main"

[dependencies.amm-v1]
local = "../razor/"

[dev-dependencies]
