[package]
name = "aptos-pump-fun"
version = "1.0.0"
authors = []

[addresses]
pump = "0xef9b17d1fb0f975e2a3adda724a25eb19c77253ceabe72c9859593219a15b0ff"
dead = "0xdead"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Liquidswap]
git = "https://github.com/pontem-network/liquidswap.git"
rev = "main"

[dependencies.razor]
local = "../razor/"

[dev-dependencies]
