[package]
name = "aptos-pump-fun"
version = "1.0.0"
authors = []

[addresses]
pump = "0x52666e7e7e2709bd4565967fcb3fe7a796e1d29ff97da8ec91620e4f90b06224"
dead = "0xdead"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

#[dependencies.Liquidswap]
#git = "https://github.com/pontem-network/liquidswap.git"
#rev = "main"

[dependencies.amm-v1]
local = "../razor/"

[dev-dependencies]
